import express from 'express';
import cors from 'cors';
import { prisma } from '@repo/database';
import { EventEmitter } from 'events';
import { videoQueue, VideoJobPayload } from '@repo/core-logic';
import { generateWeeklyStrategy } from './agents/strategy-agent';

export const globalEvents = new EventEmitter();
const app = express();

app.use(cors());
app.use(express.json());

// --- Basic API Authorization (Access Control) ---
const AUTH_TOKEN = 'ayvetsan-secret-key';
function checkAuth(req: express.Request, res: express.Response, next: express.NextFunction) {
    const authHeader = req.headers.authorization;
    if (authHeader !== `Bearer ${AUTH_TOKEN}`) {
        return res.status(401).json({ error: 'Unauthorized: Invalid API Key' });
    }
    next();
}

// --- Real-Time SSE Endpoint ---
app.get('/api/stream', (req, res) => {
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    res.flushHeaders();

    const onStateChange = (data: any) => {
        res.write(`data: ${JSON.stringify(data)}\n\n`);
    };

    globalEvents.on('stateChange', onStateChange);

    req.on('close', () => {
        globalEvents.off('stateChange', onStateChange);
    });
});

// --- Brand Onboarding API ---
app.get('/api/brand', checkAuth, async (req, res) => {
    try {
        const brand = await prisma.brandProfile.findFirst({
            orderBy: { createdAt: 'desc' }
        });
        res.json(brand || {});
    } catch (e: any) {
        res.status(500).json({ error: e.message });
    }
});

app.post('/api/brand', checkAuth, async (req, res) => {
    try {
        const { companyStory, brandValues, toneAnchor, designSpec, newsFilters } = req.body;
        const brand = await prisma.brandProfile.create({
            data: {
                companyStory: companyStory || "",
                brandValues: brandValues || "",
                toneAnchor: toneAnchor || "",
                designSpec: typeof designSpec === 'object' ? JSON.stringify(designSpec) : (designSpec || "{}"),
                newsFilters: newsFilters || ""
            }
        });
        res.json({ success: true, brand });
    } catch (e: any) {
        console.error("Brand Profile Error:", e);
        res.status(500).json({ error: e.message });
    }
});

// --- Strategy Generation API ---
app.post('/api/strategy/generate', checkAuth, async (req, res) => {
    try {
        const brand = await prisma.brandProfile.findFirst({ orderBy: { createdAt: 'desc' } });
        if (!brand) throw new Error("Please complete Brand Setup first.");

        globalEvents.emit('stateChange', { status: 'CMO Agent is planning 1-Week Strategy...' });

        const strategy = await generateWeeklyStrategy(brand);
        
        for (const item of strategy.weekPlan) {
            // V6 Pivot: Pass the actual generated Headline (topic) through the topicId, separated by a pipe for uniqueness
            const safeTopic = item.topic.replace(/['"|]/g, '');
            const topicId = `${safeTopic}|${Date.now()}_Day_${item.day}`;
            
            await prisma.contentJob.create({
                data: {
                    topicId,
                    strategy: item.strategy,
                    status: 'NEEDS_REVIEW',
                    contentType: item.contentType,
                    funnelStage: item.funnelStage,
                    contextPlatform: item.contextPlatform,
                    isEvergreen: true, // Generated by the brand CMO agent
                    bundle: {
                        create: {
                            reelsScript: item.contextPlatform === 'IG' || item.contextPlatform === 'TikTok' ? item.draftText : '',
                            caption_ig: item.contextPlatform === 'IG' ? item.draftText : '',
                            thread_x: item.contextPlatform === 'X' ? item.draftText : '',
                            post_li: item.contextPlatform === 'LinkedIn' ? item.draftText : '',
                            syntheticScore: item.syntheticScorePrediction
                        }
                    }
                }
            });
        }

        res.json({ success: true, message: "1-Week Strategy Generated Successfully" });
        globalEvents.emit('stateChange', { status: '7-Day Funnel Plan Inserted into Dashboard' });

    } catch (e: any) {
        console.error("Strategy Generation Error:", e);
        res.status(500).json({ error: e.message });
    }
});

// --- Fetch All Bundles ---
app.get('/api/bundles', checkAuth, async (req, res) => {
    try {
        const bundles = await prisma.socialBundle.findMany({
            include: { contentJob: true },
            orderBy: { createdAt: 'desc' }
        });
        
        const formatted = bundles.map(b => ({
            id: b.id,
            jobId: b.contentJobId,
            timestamp: b.createdAt.toISOString(),
            videoUrl: b.videoUrl,
            status: b.contentJob?.status || 'UNKNOWN',
            strategy: b.contentJob?.strategy || 'Unknown',
            funnelStage: b.contentJob?.funnelStage || 'ToF',
            contentType: b.contentJob?.contentType || 'REELS',
            contextPlatform: b.contentJob?.contextPlatform || 'Instagram',
            bundle: {
                reelsScript: b.reelsScript,
                storySequence: b.storySequence ? (() => { try { return JSON.parse(b.storySequence) } catch(e) { return [] } })() : [],
                caption_ig: b.caption_ig,
                thread_x: b.thread_x,
                post_li: b.post_li,
                syntheticScore: b.syntheticScore
            }
        }));
        
        res.json(formatted);
    } catch (e: any) {
        console.error(e);
        res.status(500).json({ error: e.message });
    }
});

// --- Approval Gate Logic ---
app.post('/api/bundles/:id/approve', checkAuth, async (req, res) => {
    try {
        const bundleId = req.params.id as string;
        const { reelsScript, caption_ig } = req.body; // Edited text from dashboard

        // Update DB
        const updatedBundle = await prisma.socialBundle.update({
            where: { id: bundleId },
            data: {
                reelsScript,
                caption_ig,
                contentJob: {
                    update: { status: 'PROCESSING' }
                }
            },
            include: { contentJob: true }
        });

        // Broadcast State
        globalEvents.emit('stateChange', { topicId: updatedBundle.contentJob?.topicId, status: 'PROCESSING' });

        // Push to VideoWorker via BullMQ
        const rawSeq = updatedBundle.storySequence ? JSON.parse(updatedBundle.storySequence) : [];
        const videoPayload: VideoJobPayload = {
            topicId: updatedBundle.contentJob?.topicId || "fallback-topic",
            targetPlatform: "Reels",
            strategy: (updatedBundle.contentJob?.strategy as "Authority" | "Engagement") || "Authority",
            bundle: {
                reelsScript: updatedBundle.reelsScript || "",
                storySequence: Array.isArray(rawSeq) ? rawSeq : [],
                caption_ig: updatedBundle.caption_ig || "",
                thread_x: updatedBundle.thread_x || "",
                post_li: updatedBundle.post_li || "",
                searchKeywords: ["livestock", "agriculture", "farmer"],
                visualPrompt: "Cinematic, professional, 4k, hyper-detailed"
            }
        };
        
        await videoQueue.add("render-social-bundle", videoPayload, {
            attempts: 2,
            backoff: { type: "exponential", delay: 10000 }
        });

        res.json({ success: true, message: "Approved and pushed to Video Pipeline!" });
    } catch (e: any) {
        console.error(e);
        res.status(500).json({ error: e.message });
    }
});

const PORT = 3000;
app.listen(PORT, () => console.log(`🚀 API Server running on port ${PORT}`));
